# command: conda env create -f environment.yml
name: NoBox
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cycler=0.10.0
  - dbus=1.13.12
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2020.0
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran-ng
  - libpng=1.6.37
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxml2=2.9.9
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.0.2u
  - pcre=8.43
  - pillow=6.1.0
  - pip=20.0.2
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.7.0
  - python-dateutil=2.8.1
  - pytorch
    #- pytorch=1.4.0
  - qt=5.9.6
  - readline=7.0
  - setuptools=46.1.3
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision
  - tornado=6.0.4
  - tqdm=4.43.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - advertorch==0.2.2
    - astor==0.8.1
    - backcall==0.1.0
    - chardet==3.0.4
    - click==7.1.1
    - configparser==5.0.0
    - decorator==4.4.2
    - docker-pycreds==0.4.0
    - gast==0.2.2
    - gitdb==4.0.4
    - gitpython==3.1.1
    - google-pasta==0.2.0
    - gql==0.2.0
    - graphql-core==1.1
    - grpcio==1.28.1
    - h5py==2.10.0
    - idna==2.9
    - ipdb==0.13.2
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - jedi==0.16.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - nvidia-ml-py3==7.352.0
    - opt-einsum==3.2.0
    - parso==0.7.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - promise==2.3
    - prompt-toolkit==3.0.5
    - protobuf==3.11.3
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyyaml==5.3.1
    - requests==2.23.0
    - sentry-sdk==0.14.3
    - shortuuid==1.0.1
    - smmap==3.0.2
    - subprocess32==3.5.4
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - traitlets==4.3.3
    - urllib3==1.25.9
    - wandb==0.8.32
    - watchdog==0.10.2
    - wcwidth==0.1.9
    - werkzeug==1.0.1
    - wrapt==1.12.1

